--- #YAML:1.0
name:               Win32-Wlan
version:            0.05
abstract:           Query wlan properties
author:
    - Max Maischein <corion@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:      0
    perl:        5.006
    Win32::API:  0
resources:
    repository:  http://github.com/Corion/Win32-Wlan
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
